import type { NavLink } from '.../.vitepress/theme/types'

type NavData = {
  title: string
  items: NavLink[]
}

export const NAV_DATA: NavData[] = [
  {
    title: 'Official Websites',
    items: [
      {
        //icon: 'https://www.minecraft.net/content/dam/minecraftnet/franchise/logos/Homepage_Download-Launcher_Creeper-Logo_500x500.png',
        icon: '/icons/nav/MC官方网站/Minecraft官网.avif',
        title: 'Minecraft Official Website',
        link: 'https://www.minecraft.net/',
      },
      {
        //icon: 'https://education.minecraft.net/etc.clientlibs/minecraft-edu/clientlibs/clientlib-common/resources/images/favicon/new-apple-icon.png',
        icon: '/icons/nav/MC官方网站/教育版官网.png',
        title: 'Education Edition Official Website',
        link: 'https://education.minecraft.net/',
      },
      {
        //icon: 'https://mc.163.com/favicon.ico',
        icon: '/icons/nav/MC官方网站/MC中国版官网.ico',
        title: 'Minecraft China Edition Official Website',
        link: 'https://mc.163.com/',
      },
      {
        //icon: 'https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/logos/Homepage_Gameplay-Trailer_MC-OV-logo_300x300.png',
        icon: '/icons/nav/MC官方网站/反馈社区.png',
        title: 'Feedback Community',
        desc: 'The official feedback community for Minecraft',
        link: 'https://feedback.minecraft.net/',
      },
      {
        //icon: 'https://toolb.cn/favicon/bugs.mojang.com',
        icon: '/icons/nav/MC官方网站/Mojang Jira.png',
        title: 'Mojang Jira',
        desc: 'The official bug report community for Minecraft',
        link: 'https://feedback.minecraft.net/',
      },
      {
        //icon: 'https://mc.163.com/favicon.ico',
        icon: '/icons/nav/MC官方网站/网易版论坛.ico',
        title: 'Netease Version Forum',
        desc: 'Official forum for the China Edition',
        link: 'https://mc.netease.com/',
      },
    ],
  },
  {
    title: 'Unofficial Forums',
    items: [
      {
        //icon: 'https://media.minecraftforum.net/avatars/0/1/635356669593325566.png',
        icon: '/icons/nav/非官方论坛/Minecraft Forum.webp',
        title: 'Minecraft Forum',
        desc: 'A well-known unofficial Minecraft forum abroad',
        link: 'https://www.minecraftforum.net/',
      },
      {
        icon: '/MCFlare.ico',
        title: 'MCFlare',
        desc: 'A new Minecraft Technology Exchange Community',
        link: 'https://forum.mcflare.com/',
      },
      {
        //icon: 'https://www.minebbs.com/favicon.ico',
        icon: '/icons/nav/非官方论坛/MineBBS.png',
        title: 'MineBBS',
        desc: 'A Chinese Minecraft forum in China, focusing on Bedrock Edition',
        link: 'https://www.minebbs.com/',
      },
      {
        //icon: 'https://klpbbs.com/favicon.ico',
        icon: '/icons/nav/非官方论坛/苦力怕论坛.png',
        title: 'Creeper Forum',
        desc: 'A Chinese Minecraft forum in China, focusing on Bedrock Edition',
        link: 'https://klpbbs.com/',
      },
      {
        //icon: 'https://www.himcbbs.com/favicon.ico',
        icon: '/icons/nav/非官方论坛/HiMCBBS.png',
        title: 'HiMCBBS',
        desc: 'A Chinese Minecraft forum in China, focusing on Java Edition',
        link: 'https://www.himcbbs.com/',
      },
      {
        icon: '/icons/nav/非官方论坛/小僵尸论坛.png',
        title: 'ZITBBS',
        desc: 'A Chinese Minecraft forum in China',
        link: 'https://www.zitbbs.com/',
      },
      {
        //icon: 'https://www.bangbang93.com/favicon.ico',
        icon: '/icons/nav/非官方论坛/Bangbang93论坛.ico',
        title: 'Bangbang93 Forum',
        desc: 'Host of the very famous domestic mirror for download sources—BMCLAPI',
        link: 'https://www.bangbang93.com',
      },
      {
        //icon: 'https://mcobs.fun/static/MCOBS1.png',
        icon: '/icons/nav/非官方论坛/mcobs.png',
        title: 'Obsidian Forum',
        desc: 'An emerging domestic forum, focusing on Java Edition',
        link: 'https://mcobs.cn/',
      },
    ],
  },
  {
    title: 'Wikis',
    items: [
      {
        //icon: 'https://zh.minecraft.wiki/favicon.ico',
        icon: '/icons/nav/百科/中文 Minecraft Wiki.ico',
        title: 'Chinese Minecraft Wiki',
        desc: 'The most famous and authoritative unofficial Minecraft encyclopedia website',
        link: 'https://zh.minecraft.wiki/',
      },
      {
        //icon: 'https://www.digminecraft.com/favicon.ico',
        icon: '/icons/nav/百科/DigMinecraft.ico',
        title: 'DigMinecraft',
        desc: 'An English MC encyclopedia website',
        link: 'https://www.digminecraft.com/',
      },
      {
        //icon: 'https://www.mcmod.cn/favicon.ico',
        icon: '/icons/nav/百科/MC模组百科.ico',
        title: 'MC Mod Wiki',
        desc: 'A very famous MC mod encyclopedia website in China',
        link: 'https://www.mcmod.cn/',
      },
      {
        //icon: '',
        title: 'Wiki.vg',
        desc: 'An English Minecraft development documentation repository',
        link: 'https://wiki.vg/',
      },
      {
        //icon: 'https://mineplugin.org/images/a/a6/Mineplugin_logo_2.3.png',
        icon: '/icons/nav/百科/Minecraft 插件百科.png',
        title: 'Minecraft Plugin Wiki',
        desc: 'A Chinese MC plugin encyclopedia website',
        link: 'https://mineplugin.org/',
      },
      {
        //icon: 'https://static.miraheze.org/mcpkwiki/c/c5/MCPK_logo.png',
        icon: '/icons/nav/百科/Minecraft Parkour Wiki.webp',
        title: 'Minecraft Parkour Wiki',
        desc: 'A wiki that documents MC parkour knowledge and player movement mechanics',
        link: 'https://www.mcpk.wiki/wiki/Main_Page/zh',
      },
      {
        //icon: 'https://nitwikit.8aka.org/img/book.png',
        icon: '/icons/nav/百科/笨蛋 MC 开服教程.png',
        title: 'Simple MC Server Setup Tutorial',
        desc: 'MC server setup tutorial',
        link: 'https://nitwikit.8aka.org/',
      },
    ],
  },
  {
    title: 'Bedrock Dev Docs',
    items: [
      {
        //icon: 'https://wiki.mcbe-dev.net/w/images/f/f0/Wiki.svg',
        icon: '/icons/nav/基岩版开发文档/MC基岩版开发Wiki.svg',
        title: 'Minecraft Bedrock Edition Development Wiki',
        link: 'https://wiki.mcbe-dev.net/',
      },
      {
        //icon: 'https://wiki.bedrock.dev/assets/images/homepage/wikilogo.png',
        icon: '/icons/nav/基岩版开发文档/Bedrock Wiki.png',
        title: 'Bedrock Wiki',
        link: 'https://wiki.bedrock.dev',
      },
      {
        //icon: 'https://github.com/destruc7i0n/bedrock-dot-dev/blob/master/public/favicon/apple-touch-icon.png?raw=true',
        icon: '/icons/nav/基岩版开发文档/bedrock.dev.png',
        title: 'bedrock.dev',
        link: 'https://bedrock.dev/',
      },
      {
        //icon: 'https://www.microsoft.com/favicon.ico?v2',
        icon: '/icons/nav/基岩版开发文档/MCBE 官方创作者文档.ico',
        title: 'MCBE Official Creator Documentation',
        desc: "Microsoft's official MCBE creator documentation",
        link: 'https://learn.microsoft.com/zh-cn/minecraft/creator/?view=minecraft-bedrock-stable',
      },

    ],
  },
  {
    title: 'Resource Websites',
    items: [
      {
        //icon: 'https://mcversions.net/favicon.ico',
        icon: '/icons/nav/资源站/MCVersions.ico',
        title: 'MCVersions',
        desc: 'Download JAR files for all Java Edition versions',
        link: 'https://mcversions.net/',
      },
      {
        //icon: 'https://bbk.endyun.ltd/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft for Android 版本库.ico',
        title: 'Minecraft for Android Version Repository',
        desc: 'Download Bedrock Edition for Android',
        link: 'https://bbk.endyun.ltd/',
      },
      {
        //icon: 'https://images.mcappx.com/logo/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft for Windows 版本库.ico',
        title: 'Minecraft for Windows Version Repository',
        desc: 'Download Bedrock Edition for PC',
        link: 'https://www.mcappx.com/',
      },
      {
        //icon: 'https://www.fastmirror.net/favicon.ico',
        icon: '/icons/nav/资源站/无极镜像.ico',
        title: 'FastMirror',
        desc: 'Quickly download various MC server cores',
        link: 'https://www.fastmirror.net/#/home',
      },
      {
        //icon: 'https://www.curseforge.com/favicon.ico',
        icon: '/icons/nav/资源站/CurseForge.ico',
        title: 'CurseForge',
        desc: 'A long-standing MC resource site',
        link: 'https://www.curseforge.com/minecraft',
      },
      {
        //icon: 'https://modrinth.com/favicon.ico',
        icon: '/icons/nav/资源站/Modrinth.ico',
        title: 'Modrinth',
        desc: 'An emerging third-party Minecraft resource site',
        link: 'https://modrinth.com',
      },
      {
        //icon: 'https://www.planetminecraft.com/favicon.ico',
        icon: '/icons/nav/资源站/PlanetMinecraft.ico',
        title: 'PlanetMinecraft',
        desc: 'A relatively well-known Minecraft resource website',
        link: 'https://www.planetminecraft.com/',
      },
      {
        //icon: 'https://www.spigotmc.org/favicon.ico',
        icon: '/icons/nav/资源站/SpigotMc.ico',
        title: 'SpigotMc',
        desc: 'The resources section of SpigotMc, featuring many plugins',
        link: 'https://www.spigotmc.org/resources/',
      },
      {
        //icon: 'https://hangar.papermc.io/_nuxt/hangar-logo.DNKyJEtq.svg',
        icon: '/icons/nav/资源站/Hanger.svg',
        title: 'Hangar',
        desc: 'A plugin site provided by PaperMC',
        link: 'https://hangar.papermc.io/',
      },
      {
        //icon: 'https://spongepowered.org/favicon.ico',
        icon: '/icons/nav/资源站/Sponge Ore.ico',
        title: 'Sponge Ore',
        desc: 'A download site for Sponge server plugins',
        link: 'https://ore.spongepowered.org/',
      },
      {
        //icon: 'https://mcpedl.com/favicon.ico',
        icon: '/icons/nav/资源站/MCPEDL.ico',
        title: 'MCPEDL',
        desc: 'A dedicated resource site for Minecraft Bedrock Edition',
        link: 'https://mcpedl.com/',
      },
      {
        //icon: 'https://www.minecraftyard.com/favicon.ico',
        icon: '/icons/nav/资源站/MinecraftYard.ico',
        title: 'MinecraftYard',
        desc: 'Contains some resources for Java Edition',
        link: 'https://www.minecraftyard.com/',
      },
      {
        //icon: 'https://www.minecraftmods.com/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft Mods.ico',
        title: 'Minecraft Mods',
        desc: 'Contains some mod resources for Java Edition',
        link: 'https://www.minecraftmods.com/',
      },
      {
        //icon: 'https://www.minecraftmaps.com/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft Maps.ico',
        title: 'Minecraft Maps',
        desc: 'A dedicated resource site for MC game maps',
        link: 'https://www.minecraftmaps.com/',
      },
      {
        //icon: 'https://minecraftshader.com/wp-content/uploads/2023/09/sun-favicon-e1695481883503.png',
        icon: '/icons/nav/资源站/Minecraft Shaders.avif',
        title: 'Minecraft Shaders',
        desc: 'Provides shader packs and resource pack resources for MC',
        link: 'https://minecraftshader.com/',
      },
      {
        //icon: 'https://resourcepack.net/wp-content/themes/rp/assets/images/ico-diamond.png',
        icon: '/icons/nav/资源站/Resourse Packs for Minecraft.png',
        title: 'Resource Packs for Minecraft',
        desc: 'Mainly provides various resource pack resources for MC',
        link: 'https://resourcepack.net/',
      },
      {
        //icon: 'https://littleskin.cn/favicon.png',
        icon: '/icons/nav/资源站/LittleSkin.png',
        title: 'LittleSkin',
        desc: 'A long-standing MC skin site in China',
        link: 'https://littleskin.cn/',
      },
      {
        //icon: 'https://www.minecraftskins.com/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft Skins.ico',
        title: 'Minecraft Skins',
        desc: 'An English MC skin resource website',
        link: 'https://www.minecraftskins.com/',
      },
      {
        //icon: 'https://mskins.net/favicon.ico',
        icon: '/icons/nav/资源站/MSkins.ico',
        title: 'MSkins',
        desc: 'An English MC skin resource website',
        link: 'https://mskins.net/',
      },
      {
        //icon: 'https://www.minecraft-schematics.com/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft Schematics.ico',
        title: 'Minecraft Schematics',
        desc: 'An English MC schematic resource website',
        link: 'https://www.minecraft-schematics.com/',
      },
      {
        icon: '/icons/nav/资源站/Minecraft_Sounds.webp',
        title: 'Minecraft Sounds',
        desc: 'A Chinese website for downloading MC sound effects',
        link: 'https://o.xbottle.top/mcsounds/',
      },
    ],
  },
  {
    title: 'Server Gateways',
    items: [
      {
        icon: '/logo.png',
        title: 'MCJPG Organization',
        desc: 'Official website of the MCJPG Organization',
        link: 'https://mcjpg.org',
      },
      {
        icon: '/icons/nav/服务器门户/MSCPO.webp',
        title: 'MSCPO',
        desc: 'A collective server promotion organization',
        link: 'https://mscpo.top/',
      },
      {
        //icon: 'https://toolb.cn/favicon/minecraftservers.org',
        icon: '/icons/nav/服务器门户/Minecraft Servers.png',
        title: 'Minecraft Servers',
        desc: 'A relatively well-known server resource website abroad',
        link: 'https://minecraftservers.org/',
      },
      {
        //icon: 'https://minecraft-mp.com/favicon.ico',
        icon: '/icons/nav/服务器门户/Minecraft Multiplayer.ico',
        title: 'Minecraft Multiplayer',
        desc: 'A relatively well-known server resource website abroad',
        link: 'https://minecraft-mp.com/',
      },
      {
        //icon: 'https://www.mclists.cn/template/images/favicon.ico',
        icon: '/icons/nav/服务器门户/我的世界找服网.ico',
        title: 'Minecraft Server Finder',
        desc: 'A domestic server resource website in China',
        link: 'https://www.mczfw.cn/',
      },
      {
        //icon: 'https://cdn.mczfw.cn/images/logo.png',
        icon: '/icons/nav/服务器门户/Minecraft服务器列表.png',
        title: 'Minecraft Server List',
        desc: 'A domestic server resource website in China',
        link: 'https://www.mczfw.cn/',
      },
      {
        //icon: 'https://www.mcmod.cn/favicon.ico',
        icon: '/icons/nav/服务器门户/MCMOD服务器列表.ico',
        title: 'MCMOD Server List',
        desc: 'The server section of MCMOD',
        link: 'https://play.mcmod.cn/',
      },
    ],
  },
  {
    title: 'Functional Websites',
    items: [
      {
        //icon: 'https://www.chunkbase.com/favicon.ico',
        icon: '/icons/nav/功能性网站/Chunk Base.ico',
        title: 'Chunk Base',
        desc: 'A tool website for seed finders, chunk viewers, etc.',
        link: 'https://www.chunkbase.com/',
      },
      {
        //icon: 'http://mcid.lingningyu.cn/webIcon_mcid.png',
        icon: '/icons/nav/功能性网站/MCID.png',
        title: 'MCID',
        desc: 'Item ID lookup website',
        link: 'http://mcid.lingningyu.cn/',
      },
      {
        //icon: 'https://minecraft.tools/favicon.ico',
        icon: '/icons/nav/功能性网站/Minecraft Tools.ico',
        title: 'Minecraft Tools',
        desc: 'Provides various tools for customization and more',
        link: 'https://minecraft.tools/',
      },
      {
        //icon: 'https://mctools.org/img/icon.png',
        icon: '/icons/nav/功能性网站/Minecraft Server Tools.png',
        title: 'Minecraft Server Tools',
        desc: 'Provides various tools for customizing servers',
        link: 'https://mctools.org/',
      },
      {
        //icon: 'https://mcsrvstat.us/img/minecraft.png',
        icon: '/icons/nav/功能性网站/Minecraft Server Status.png',
        title: 'Minecraft Server Status',
        desc: 'Web-based MC server status checker',
        link: 'https://mcsrvstat.us/',
      },
      {
        //icon: 'https://mcstatus.io/favicon.ico',
        icon: '/icons/nav/功能性网站/MCS.ico',
        title: 'MCS',
        desc: 'Web-based MC server status checker',
        link: 'https://mcstatus.io/',
      },
      {
        //icon: 'https://mclo.gs/img/favicon.ico',
        icon: '/icons/nav/功能性网站/mclo.gs.ico',
        title: 'mclo.gs',
        desc: 'MC server log analysis',
        link: 'https://mclo.gs/',
      },
      {
        //icon: 'https://redenmc.com/reden_256.png',
        icon: '/icons/nav/功能性网站/Reden.png',
        title: 'Reden',
        desc: 'Online generator for schematic files like world eaters',
        link: 'https://redenmc.com/',
      },
      {
        //icon: 'https://rebane2001.com/mapartcraft/images/favicon.ico',
        icon: '/icons/nav/功能性网站/MapartCraft.ico',
        title: 'MapartCraft',
        desc: 'MC pixel art generator, supports schematics',
        link: 'https://rebane2001.com/mapartcraft/zh-Hans',
      },
      {
        //icon: 'https://www.minecraftpfp.com/PFP/I_Like_Cats__.png',
        icon: '/icons/nav/功能性网站/Minecraft PFP.png',
        title: 'Minecraft PFP',
        desc: 'Generates profile pictures based on premium account skins',
        link: 'https://www.minecraftpfp.com/',
      },
      {
        //icon: 'https://www.gamergeeks.net/favicon.ico',
        icon: '/icons/nav/功能性网站/GAMEGEEKS.ico',
        title: 'GAMEGEEKS',
        desc: 'Web-based MC command generator',
        link: 'https://www.gamergeeks.net/',
      },
      {
        //icon: 'https://wallpapers.novaskin.me/apple-touch-icon.png',
        icon: '/icons/nav/功能性网站/Nova Skin.png',
        title: 'Nova Skin',
        desc: 'A web-based MC skin site for creating, uploading skins, and downloading skin-based wallpapers',
        link: 'https://minecraft.novaskin.me/',
      },
      {
        //icon: 'https://skin.endyun.ltd/img/favicon.ico',
        icon: '/icons/nav/功能性网站/MC-3D皮肤预览.ico',
        title: 'MC-3D Skin Preview',
        desc: 'MC skin lookup and 3D preview',
        link: 'https://skin.endyun.ltd/',
      },
      {
        //icon: 'https://textcraft.net/favicon.ico',
        icon: '/icons/nav/功能性网站/Textcraft.ico',
        title: 'Textcraft',
        desc: 'Generate various Minecraft-style text art',
        link: 'https://textcraft.net/',
      },
      {
        //icon: 'https://chunker.app/favicon.png',
        icon: '/icons/nav/功能性网站/Chunker.png',
        title: 'Chunker',
        desc: 'Online MC cross-version map converter, supports JE<>BE conversion',
        link: 'https://chunker.app/',
      },
      {
        //icon: 'https://minecraft-heads.com/themes/mch-v2/assets/images/chest.webp',
        icon: '/icons/nav/功能性网站/Minecraft Heads.webp',
        title: 'Minecraft Heads',
        desc: 'A large collection of decorative MC heads',
        link: 'https://www.minecraft-heads.com/',
      },
      {
        //icon: 'https://minecraftshapes.com/favicon.ico',
        icon: '/icons/nav/功能性网站/Minecraft Shapes.ico',
        title: 'Minecraft Shapes',
        desc: 'Guides for building regular shapes in MC',
        link: 'https://minecraftshapes.com/',
      },
      {
        //icon: 'https://zh-cn.namemc.com/favicon.ico',
        icon: '/icons/nav/功能性网站/NameMC.ico',
        title: 'NameMC',
        desc: 'Look up premium player info like name, skin, UUID, etc.',
        link: 'https://zh-cn.namemc.com/',
      },
      {
        //icon: 'https://mcuuid.net/favicon.ico',
        icon: '/icons/nav/功能性网站/Minecraft UUID.ico',
        title: 'Minecraft UUID',
        desc: "Look up a premium player's UUID and other info",
        link: 'https://mcuuid.net/',
      },
    ],
  },
  {
    title: 'Mod and Shader Loaders',
    items: [
      {
        //icon: 'https://forums.minecraftforge.net/favicon.ico',
        icon: '/icons/nav/模组和光影加载器/Forge.ico',
        title: 'Forge',
        desc: 'Official website of the long-standing mod loader',
        link: 'https://forums.minecraftforge.net/',
      },
      {
        //icon: 'https://neoforged.net/favicon.ico',
        icon: '/icons/nav/模组和光影加载器/NeoForge.ico',
        title: 'NeoForge',
        desc: 'A better fork of Forge for newer versions',
        link: 'https://neoforged.net/',
      },
      {
        //icon: 'https://fabricmc.net/assets/logo.png',
        icon: '/icons/nav/模组和光影加载器/Fabric.png',
        title: 'Fabric',
        desc: 'An emerging and popular mod loader',
        link: 'https://fabricmc.net/',
      },
      {
        //icon: 'https://quiltmc.org/favicon/favicon-32x32.png',
        icon: '/icons/nav/模组和光影加载器/Quilt.webp',
        title: 'Quilt',
        desc: 'A downstream fork of Fabric',
        link: 'https://quiltmc.org/en/',
      },
      {
        //icon: 'https://www.liteloader.com/favicon.ico',
        icon: '/icons/nav/模组和光影加载器/LiteLoader.ico',
        title: 'LiteLoader',
        desc: 'A lightweight mod loader, not updated for a while',
        link: 'http://www.liteloader.com/',
      },
      {
        //icon: 'https://www.optifine.net/favicon.ico',
        icon: '/icons/nav/模组和光影加载器/Optifine.ico',
        title: 'Optifine',
        desc: 'A long-standing rendering optimization mod (HD texture fix), also acts as a shader loader',
        link: 'https://www.optifine.net',
      },
      {
        //icon: 'https://cdn.modrinth.com/data/YL57xq9U/dc558eece920db435f9823ce86de0c4cde89800b.png',
        icon: '/icons/nav/模组和光影加载器/Iris Shaders.webp',
        title: 'Iris Shaders',
        desc: 'A shader loader for modern Java Edition powered by Fabric, compatible with Sodium',
        link: 'https://irisshaders.net/',
      },
    ],
  },
  {
    title: 'Launchers and Clients',
    items: [
      {
        //icon: 'https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/img/Launcher_Icon.png',
        icon: '/icons/nav/启动器和客户端/Minecraft 官方启动器.avif',
        title: 'Minecraft Official Launcher',
        desc: 'The official MC launcher',
        link: 'https://www.minecraft.net/zh-hans/download',
      },
      {
        //icon: 'https://hmcl.huangyuhui.net/favicon.ico',
        icon: '/icons/nav/启动器和客户端/HMCL.ico',
        title: 'HMCL',
        desc: 'A classic, long-standing, cross-platform launcher',
        link: 'https://hmcl.huangyuhui.net/',
      },
      {
        //icon: '/icons/PCL2.png',
        icon: '/icons/nav/启动器和客户端/PCL2.png',
        title: 'PCL2',
        desc: 'An emerging launcher, suitable for beginners',
        link: 'https://afdian.com/p/0164034c016c11ebafcb52540025c377',

      },
      {
        //icon: 'https://www.bakaxl.com/favicon.ico',
        icon: '/icons/nav/启动器和客户端/BakaXL.ico',
        title: 'BakaXL',
        desc: 'A domestic anime-style launcher with a beautiful interface',
        link: 'https://www.bakaxl.com/',
      },
      {
        //icon: 'https://multimc.org/favicon.ico',
        icon: '/icons/nav/启动器和客户端/MultiMC.ico',
        title: 'MultiMC',
        desc: 'A long-standing international launcher, supports Chinese',
        link: 'https://multimc.org/',
      },
      {
        //icon: 'https://mc.163.com/favicon.ico',
        icon: '/icons/nav/启动器和客户端/中国版启动器.ico',
        title: 'China Edition Launcher',
        desc: 'Official website for the China Edition',
        link: 'https://mc.163.com/',
      },
      {
        //icon: 'https://www.lunarclient.com/assets/img/favicon.ico',
        icon: '/icons/nav/启动器和客户端/Lunar Client.ico',
        title: 'Lunar Client',
        desc: 'A popular PvP client',
        link: 'https://www.lunarclient.com/',
      },
      {
        //icon: 'https://assets.badlion.net/site/favicon.webp',
        icon: '/icons/nav/启动器和客户端/Badlion Client.webp',
        title: 'Badlion Client',
        desc: 'A popular PvP client',
        link: 'https://client.badlion.net/zh-CN',
      },
      {
        //icon: 'https://labymod.net/page/tpl/assets/images/icons/favicon.ico',
        icon: '/icons/nav/启动器和客户端/Labymod.ico',
        title: 'Labymod',
        desc: 'A popular PvP client',
        link: 'https://labymod.net/zh_Hans',
      },
      {
        //icon: 'https://feathermc.com/favicon/apple-touch-icon.png',
        icon: '/icons/nav/启动器和客户端/FEATHER CLIENT.png',
        title: 'FEATHER CLIENT',
        desc: 'A popular PvP client',
        link: 'https://feathermc.com/',
      },
    ],
  },
  {
    title: 'Practical Software',
    items: [
      {
        icon: '/icons/nav/实用软件/EaglerCraft.webp',
        title: 'EaglerCraftX',
        desc: 'Web-based Minecraft, version JE 1.8.8',
        link: 'https://eaglercraft.ru/',
      },
      {
        //icon: 'https://mccteam.github.io/icons/favicon-32x32.png',
        icon: '/icons/nav/实用软件/MCC.png',
        title: 'MCC',
        desc: 'Minecraft Command-line Client',
        link: 'https://mccteam.github.io/l10n/zh-Hans/',
      },
      {
        //icon: '/icons/MCA.png',
        icon: '/icons/nav/实用软件/MCA Selector.png',
        title: 'MCA Selector',
        desc: 'An MC chunk selector for easy chunk editing, supports Chinese',
        link: 'https://github.com/Querz/mcaselector',
      },
      {
        //icon: 'https://www.worldpainter.net/favicon.ico',
        icon: '/icons/nav/实用软件/WorldPainter.ico',
        title: 'WorldPainter',
        desc: 'MC terrain creation software',
        link: 'https://www.worldpainter.net/',
      },
      {
        //icon: 'https://www.radmin.com/favicon.svg',
        icon: '/icons/nav/实用软件/Radmin LAN.svg',
        title: 'Radmin LAN',
        desc: 'Virtual LAN software, can be used for multiplayer',
        link: 'https://www.radmin.com/cn/',
      },
      {
        //icon: 'https://www.mineimator.com/images/logo.png',
        icon: '/icons/nav/实用软件/Mine-imator.png',
        title: 'Mine-imator',
        desc: 'MC animation creation software',
        link: 'https://www.mineimator.com/',
      },
      {
        //icon: 'https://mcreator.net/themes/mcreator/favicon.ico',
        icon: '/icons/nav/实用软件/MCreator.ico',
        title: 'MCreator',
        desc: 'Visual MC mod creation software',
        link: 'https://mcreator.net/',
      },
      {
        //icon: 'https://www.blockbench.net/favicon.svg',
        icon: '/icons/nav/实用软件/BlockBench.svg',
        title: 'BlockBench',
        desc: 'MC modeling software',
        link: 'https://www.blockbench.net/',
      },
      {
        //icon: 'https://serverpackcreator.de/icons/favicon-128x128.png',
        icon: '/icons/nav/实用软件/ServerPackCreator.png',
        title: 'ServerPackCreator',
        desc: 'Generates server cores for modded servers',
        link: 'https://serverpackcreator.de/#/',
      },
    ],
  },
]
