import type { NavLink } from '../.vitepress/theme/types'

type NavData = {
  title: string
  items: NavLink[]
}

export const NAV_DATA: NavData[] = [
  {
    title: 'MC官府網驛',
    items: [
      {
        //icon: 'https://www.minecraft.net/content/dam/minecraftnet/franchise/logos/Homepage_Download-Launcher_Creeper-Logo_500x500.png',
        icon: '/icons/nav/MC官方网站/Minecraft官网.avif',
        title: 'Minecraft官網',
        link: 'https://www.minecraft.net/',
      },
      {
        //icon: 'https://education.minecraft.net/etc.clientlibs/minecraft-edu/clientlibs/clientlib-common/resources/images/favicon/new-apple-icon.png',
        icon: '/icons/nav/MC官方网站/教育版官网.png',
        title: '教化版官網',
        link: 'https://education.minecraft.net/',
      },
      {
        //icon: 'https://mc.163.com/favicon.ico',
        icon: '/icons/nav/MC官方网站/MC中国版官网.ico',
        title: 'MC華夏版官網',
        link: 'https://mc.163.com/',
      },
      {
        //icon: 'https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/logos/Homepage_Gameplay-Trailer_MC-OV-logo_300x300.png',
        icon: '/icons/nav/MC官方网站/反馈社区.png',
        title: '建言堂',
        desc: 'MC官府之建言堂也',
        link: 'https://feedback.minecraft.net/',
      },
      {
        //icon: 'https://toolb.cn/favicon/bugs.mojang.com',
        icon: '/icons/nav/MC官方网站/Mojang Jira.png',
        title: 'Mojang Jira',
        desc: 'MC官府勘誤之所',
        link: 'https://feedback.minecraft.net/',
      },
      {
        //icon: 'https://mc.163.com/favicon.ico',
        icon: '/icons/nav/MC官方网站/网易版论坛.ico',
        title: '網易版論壇',
        desc: '華夏版官府論壇',
        link: 'https://mc.netease.com/',
      },
    ],
  },
  {
    title: '民間論壇',
    items: [
      {
        //icon: 'https://media.minecraftforum.net/avatars/0/1/635356669593325566.png',
        icon: '/icons/nav/非官方论坛/Minecraft Forum.webp',
        title: 'Minecraft Forum',
        desc: '海外頗負盛名之Minecraft民間論壇',
        link: 'https://www.minecraftforum.net/',
      },
      {
        icon: '/MCFlare.ico',
        title: 'MCFlare',
        desc: 'Minecraft新立技藝論道之社',
        link: 'https://forum.mcflare.com/',
      },
      {
        //icon: 'https://www.minebbs.com/favicon.ico',
        icon: '/icons/nav/非官方论坛/MineBBS.png',
        title: 'MineBBS',
        desc: '中華Minecraft論壇也，主營基岩版',
        link: 'https://www.minebbs.com/',
      },
      {
        //icon: 'https://klpbbs.com/favicon.ico',
        icon: '/icons/nav/非官方论坛/苦力怕论坛.png',
        title: '苦力怕論壇',
        desc: '中華Minecraft論壇也，主營基岩版',
        link: 'https://klpbbs.com/',
      },
      {
        //icon: 'https://www.himcbbs.com/favicon.ico',
        icon: '/icons/nav/非官方论坛/HiMCBBS.png',
        title: 'HiMCBBS',
        desc: '中華Minecraft論壇也，主營Java版',
        link: 'https://www.himcbbs.com/',
      },
      {
        icon: '/icons/nav/非官方论坛/小僵尸论坛.png',
        title: 'ZITBBS',
        desc: '中華Minecraft論壇也',
        link: 'https://www.zitbbs.com/',
      },
      {
        //icon: 'https://www.bangbang93.com/favicon.ico',
        icon: '/icons/nav/非官方论坛/Bangbang93论坛.ico',
        title: 'Bangbang93論壇',
        desc: '下載源BMCLAPI之鏡像站，頗負盛名',
        link: 'https://www.bangbang93.com',
      },
      {
        //icon: 'https://mcobs.fun/static/MCOBS1.png',
        icon: '/icons/nav/非官方论坛/mcobs.png',
        title: '黑曜石論壇',
        desc: '中華新晉論壇也，主營java版',
        link: 'https://mcobs.cn/',
      },
    ],
  },
  {
    title: '萬物紀',
    items: [
      {
        //icon: 'https://zh.minecraft.wiki/favicon.ico',
        icon: '/icons/nav/百科/中文 Minecraft Wiki.ico',
        title: '中文 Minecraft Wiki',
        desc: 'Minecraft民間典籍之最，博洽權威',
        link: 'https://zh.minecraft.wiki/',
      },
      {
        //icon: 'https://www.digminecraft.com/favicon.ico',
        icon: '/icons/nav/百科/DigMinecraft.ico',
        title: 'DigMinecraft',
        desc: '西文MC典籍之站',
        link: 'https://www.digminecraft.com/',
      },
      {
        //icon: 'https://www.mcmod.cn/favicon.ico',
        icon: '/icons/nav/百科/MC模组百科.ico',
        title: 'MC模組百科',
        desc: '中華頗負盛名之MC模組典籍',
        link: 'https://www.mcmod.cn/',
      },
      {
        //icon: '',
        title: 'Wiki.vg',
        desc: '西文Minecraft開發文庫',
        link: 'https://wiki.vg/',
      },
      {
        //icon: 'https://mineplugin.org/images/a/a6/Mineplugin_logo_2.3.png',
        icon: '/icons/nav/百科/Minecraft 插件百科.png',
        title: 'Minecraft 插件百科',
        desc: '華夏MC插件典籍之站',
        link: 'https://mineplugin.org/',
      },
      {
        //icon: 'https://static.miraheze.org/mcpkwiki/c/c5/MCPK_logo.png',
        icon: '/icons/nav/百科/Minecraft Parkour Wiki.webp',
        title: 'Minecraft Parkour Wiki',
        desc: '此Wiki所錄，MC跑酷之技、遊者動靜之法也',
        link: 'https://www.mcpk.wiki/wiki/Main_Page/zh',
      },
      {
        //icon: 'https://nitwikit.8aka.org/book.png',
        icon: '/icons/nav/百科/笨蛋 MC 开服教程.png',
        title: '笨蛋 MC 開服教程',
        desc: 'MC開服之教程',
        link: 'https://nitwikit.8aka.org/',
      },
    ],
  },
  {
    title: '基岩版開發典籍',
    items: [
      {
        //icon: 'https://wiki.mcbe-dev.net/w/images/f/f0/Wiki.svg',
        icon: '/icons/nav/基岩版开发文档/MC基岩版开发Wiki.svg',
        title: 'MC基岩版開發Wiki',
        link: 'https://wiki.mcbe-dev.net/',
      },
      {
        //icon: 'https://wiki.bedrock.dev/assets/images/homepage/wikilogo.png',
        icon: '/icons/nav/基岩版开发文档/Bedrock Wiki.png',
        title: 'Bedrock Wiki',
        link: 'https://wiki.bedrock.dev',
      },
      {
        //icon: 'https://github.com/destruc7i0n/bedrock-dot-dev/blob/master/public/favicon/apple-touch-icon.png?raw=true',
        icon: '/icons/nav/基岩版开发文档/bedrock.dev.png',
        title: 'bedrock.dev',
        link: 'https://bedrock.dev/',
      },
      {
        //icon: 'https://www.microsoft.com/favicon.ico?v2',
        icon: '/icons/nav/基岩版开发文档/MCBE 官方创作者文档.ico',
        title: 'MCBE 官府創作者典籍',
        desc: '微軟官府MCBE創作者之典籍',
        link: 'https://learn.microsoft.com/zh-cn/minecraft/creator/?view=minecraft-bedrock-stable',
      },
    ],
  },
  {
    title: '資材之所',
    items: [
      {
        //icon: 'https://mcversions.net/favicon.ico',
        icon: '/icons/nav/资源站/MCVersions.ico',
        title: 'MCVersions',
        desc: 'Java版諸本jar之載所',
        link: 'https://mcversions.net/',
      },
      {
        //icon: 'https://bbk.endyun.ltd/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft for Android 版本库.ico',
        title: 'Minecraft for Android 版本庫',
        desc: '安卓基岩版之載所',
        link: 'https://bbk.endyun.ltd/',
      },
      {
        //icon: 'https://images.mcappx.com/logo/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft for Windows 版本库.ico',
        title: 'Minecraft for Windows 版本庫',
        desc: 'PC基岩版之載所',
        link: 'https://www.mcappx.com/',
      },
      {
        //icon: 'https://www.fastmirror.net/favicon.ico',
        icon: '/icons/nav/资源站/无极镜像.ico',
        title: 'FastMirror 無極鏡像',
        desc: '速取MC諸伺服器核心',
        link: 'https://www.fastmirror.net/#/home',
      },
      {
        //icon: 'https://www.curseforge.com/favicon.ico',
        icon: '/icons/nav/资源站/CurseForge.ico',
        title: 'CurseForge',
        desc: 'MC資材老鋪',
        link: 'https://www.curseforge.com/minecraft',
      },
      {
        //icon: 'https://modrinth.com/favicon.ico',
        icon: '/icons/nav/资源站/Modrinth.ico',
        title: 'Modrinth',
        desc: '新晉之Minecraft民間資材之所',
        link: 'https://modrinth.com',
      },
      {
        //icon: 'https://www.planetminecraft.com/favicon.ico',
        icon: '/icons/nav/资源站/PlanetMinecraft.ico',
        title: 'PlanetMinecraft',
        desc: '頗負盛名之Minecraft資材之站',
        link: 'https://www.planetminecraft.com/',
      },
      {
        //icon: 'https://www.spigotmc.org/favicon.ico',
        icon: '/icons/nav/资源站/SpigotMc.ico',
        title: 'SpigotMc',
        desc: 'SpigotMc之資材部，插件甚繁',
        link: 'https://www.spigotmc.org/resources/',
      },
      {
        //icon: 'https://hangar.papermc.io/_nuxt/hangar-logo.DNKyJEtq.svg',
        icon: '/icons/nav/资源站/Hanger.svg',
        title: 'Hanger',
        desc: 'papermc所設之插件站也',
        link: 'https://hangar.papermc.io/',
      },
      {
        //icon: 'https://spongepowered.org/favicon.ico',
        icon: '/icons/nav/资源站/Sponge Ore.ico',
        title: 'Sponge Ore',
        desc: 'Sponge伺服器插件之載所',
        link: 'https://ore.spongepowered.org/',
      },
      {
        //icon: 'https://mcpedl.com/favicon.ico',
        icon: '/icons/nav/资源站/MCPEDL.ico',
        title: 'MCPEDL',
        desc: 'MC基岩版專有之資材站',
        link: 'https://mcpedl.com/',
      },
      {
        //icon: 'https://www.minecraftyard.com/favicon.ico',
        icon: '/icons/nav/资源站/MinecraftYard.ico',
        title: 'MinecraftYard',
        desc: '收Java版資材若干',
        link: 'https://www.minecraftyard.com/',
      },
      {
        //icon: 'https://www.minecraftmods.com/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft Mods.ico',
        title: 'Minecraft Mods',
        desc: '收Java版模組資材若干',
        link: 'https://www.minecraftmods.com/',
      },
      {
        //icon: 'https://www.minecraftmaps.com/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft Maps.ico',
        title: 'Minecraft Maps',
        desc: 'MC輿圖專有之資材站',
        link: 'https://www.minecraftmaps.com/',
      },
      {
        //icon: 'https://minecraftshader.com/wp-content/uploads/2023/09/sun-favicon-e1695481883503.png',
        icon: '/icons/nav/资源站/Minecraft Shaders.avif',
        title: 'Minecraft Shaders',
        desc: '供MC光影、資材之屬',
        link: 'https://minecraftshader.com/',
      },
      {
        //icon: 'https://resourcepack.net/wp-content/themes/rp/assets/images/ico-diamond.png',
        icon: '/icons/nav/资源站/Resourse Packs for Minecraft.png',
        title: 'Resourse Packs for Minecraft',
        desc: '主供MC各類資材之屬',
        link: 'https://resourcepack.net/',
      },
      {
        //icon: 'https://littleskin.cn/favicon.png',
        icon: '/icons/nav/资源站/LittleSkin.png',
        title: 'LittleSkin',
        desc: '中華MC皮膚老鋪',
        link: 'https://littleskin.cn/',
      },
      {
        //icon: 'https://www.minecraftskins.com/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft Skins.ico',
        title: 'Minecraft Skins',
        desc: '西文MC皮膚資材之站',
        link: 'https://www.minecraftskins.com/',
      },
      {
        //icon: 'https://mskins.net/favicon.ico',
        icon: '/icons/nav/资源站/MSkins.ico',
        title: 'MSkins',
        desc: '西文MC皮膚資材之站',
        link: 'https://mskins.net/',
      },
      {
        //icon: 'https://www.minecraft-schematics.com/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft Schematics.ico',
        title: 'Minecraft Schematics',
        desc: '西文MC投影資材之站',
        link: 'https://www.minecraft-schematics.com/',
      },
      {
        icon: '/icons/nav/资源站/Minecraft_Sounds.webp',
        title: 'Minecraft Sounds',
        desc: '中華MC音效下載之站',
        link: 'https://o.xbottle.top/mcsounds/',
      },
    ],
  },
  {
    title: '伺服之門',
    items: [
      {
        icon: '/logo.png',
        title: 'MCJPG組織',
        desc: 'MCJPG組織官網',
        link: 'https://mcjpg.org',
      },
      {
        icon: '/icons/nav/服务器门户/MSCPO.webp',
        title: 'MSCPO',
        desc: '伺服群宣之組織',
        link: 'https://mscpo.top/',
      },
      {
        //icon: 'https://toolb.cn/favicon/minecraftservers.org',
        icon: '/icons/nav/服务器门户/Minecraft Servers.png',
        title: 'Minecraft Servers',
        desc: '海外頗負盛名之伺服資材站',
        link: 'https://minecraftservers.org/',
      },
      {
        //icon: 'https://minecraft-mp.com/favicon.ico',
        icon: '/icons/nav/服务器门户/Minecraft Multiplayer.ico',
        title: 'Minecraft Multiplayer',
        desc: '海外頗負盛名之伺服資材站',
        link: 'https://minecraft-mp.com/',
      },
      {
        //icon: 'https://www.mclists.cn/template/images/favicon.ico',
        icon: '/icons/nav/服务器门户/我的世界找服网.ico',
        title: '我的世界找服網',
        desc: '中華伺服資材之站',
        link: 'https://www.mczfw.cn/',
      },
      {
        //icon: 'https://cdn.mczfw.cn/images/logo.png',
        icon: '/icons/nav/服务器门户/Minecraft服务器列表.png',
        title: 'Minecraft伺服器列表',
        desc: '中華伺服資材之站',
        link: 'https://www.mczfw.cn/',
      },
      {
        //icon: 'https://www.mcmod.cn/favicon.ico',
        icon: '/icons/nav/服务器门户/MCMOD服务器列表.ico',
        title: 'MCMOD伺服器列表',
        desc: 'MCMOD之伺服部',
        link: 'https://play.mcmod.cn/',
      },
    ],
  },
  {
    title: '百工之站',
    items: [
      {
        //icon: 'https://www.chunkbase.com/favicon.ico',
        icon: '/icons/nav/功能性网站/Chunk Base.ico',
        title: 'Chunk Base',
        desc: '種子、區塊之查考工具站也',
        link: 'https://www.chunkbase.com/',
      },
      {
        //icon: 'http://mcid.lingningyu.cn/webIcon_mcid.png',
        icon: '/icons/nav/功能性网站/MCID.png',
        title: 'MCID',
        desc: '物品牌號查考之站',
        link: 'http://mcid.lingningyu.cn/',
      },
      {
        //icon: 'https://minecraft.tools/favicon.ico',
        icon: '/icons/nav/功能性网站/Minecraft Tools.ico',
        title: 'Minecraft Tools',
        desc: '備各類自定之工具',
        link: 'https://minecraft.tools/',
      },
      {
        //icon: 'https://mctools.org/img/icon.png',
        icon: '/icons/nav/功能性网站/Minecraft Server Tools.png',
        title: 'Minecraft Server Tools',
        desc: '備各類自定伺服器之工具',
        link: 'https://mctools.org/',
      },
      {
        //icon: 'https://mcsrvstat.us/img/minecraft.png',
        icon: '/icons/nav/功能性网站/Minecraft Server Status.png',
        title: 'Minecraft Server Status',
        desc: '網頁查MC伺服器狀態',
        link: 'https://mcsrvstat.us/',
      },
      {
        //icon: 'https://mcstatus.io/favicon.ico',
        icon: '/icons/nav/功能性网站/MCS.ico',
        title: 'MCS',
        desc: '網頁查MC伺服器狀態',
        link: 'https://mcstatus.io/',
      },
      {
        //icon: 'https://mclo.gs/img/favicon.ico',
        icon: '/icons/nav/功能性网站/mclo.gs.ico',
        title: 'mclo.gs',
        desc: '析MC伺服器日誌',
        link: 'https://mclo.gs/',
      },
      {
        //icon: 'https://redenmc.com/reden_256.png',
        icon: '/icons/nav/功能性网站/Reden.png',
        title: 'Reden',
        desc: '世吞等投影文檔在線生成',
        link: 'https://redenmc.com/',
      },
      {
        //icon: 'https://rebane2001.com/mapartcraft/images/favicon.ico',
        icon: '/icons/nav/功能性网站/MapartCraft.ico',
        title: 'MapartCraft',
        desc: 'MC像素畫生成器，可投影',
        link: 'https://rebane2001.com/mapartcraft/zh-Hans',
      },
      {
        //icon: 'https://www.minecraftpfp.com/PFP/I_Like_Cats__.png',
        icon: '/icons/nav/功能性网站/Minecraft PFP.png',
        title: 'Minecraft PFP',
        desc: '據正版賬號皮膚生成頭像',
        link: 'https://www.minecraftpfp.com/',
      },
      {
        //icon: 'https://www.gamergeeks.net/favicon.ico',
        icon: '/icons/nav/功能性网站/GAMEGEEKS.ico',
        title: 'GAMEGEEKS',
        desc: '網頁生成MC指令',
        link: 'https://www.gamergeeks.net/',
      },
      {
        //icon: 'https://wallpapers.novaskin.me/apple-touch-icon.png',
        icon: '/icons/nav/功能性网站/Nova Skin.png',
        title: 'Nova Skin',
        desc: '網頁MC皮膚站，可制、傳皮膚，亦可下載皮膚壁紙',
        link: 'https://minecraft.novaskin.me/',
      },
      {
        //icon: 'https://skin.endyun.ltd/img/favicon.ico',
        icon: '/icons/nav/功能性网站/MC-3D皮肤预览.ico',
        title: 'MC-3D皮膚預覽',
        desc: 'MC皮膚查考、3D預覽',
        link: 'https://skin.endyun.ltd/',
      },
      {
        //icon: 'https://textcraft.net/favicon.ico',
        icon: '/icons/nav/功能性网站/Textcraft.ico',
        title: 'Textcraft',
        desc: '生成MC風格各類書藝',
        link: 'https://textcraft.net/',
      },
      {
        //icon: 'https://chunker.app/favicon.png',
        icon: '/icons/nav/功能性网站/Chunker.png',
        title: 'Chunker',
        desc: '在線MC跨版輿圖轉換器，JE、BE可互轉',
        link: 'https://chunker.app/',
      },
      {
        //icon: 'https://minecraft-heads.com/themes/mch-v2/assets/images/chest.webp',
        icon: '/icons/nav/功能性网站/Minecraft Heads.webp',
        title: 'Minecraft Heads',
        desc: '集MC飾用頭顱甚眾',
        link: 'https://www.minecraft-heads.com/',
      },
      {
        //icon: 'https://minecraftshapes.com/favicon.ico',
        icon: '/icons/nav/功能性网站/Minecraft Shapes.ico',
        title: 'Minecraft Shapes',
        desc: '教習於MC中建合規範式之圖形',
        link: 'https://minecraftshapes.com/',
      },
      {
        //icon: 'https://zh-cn.namemc.com/favicon.ico',
        icon: '/icons/nav/功能性网站/NameMC.ico',
        title: 'NameMC',
        desc: '查正版遊者名號、皮膚、UUID等資訊',
        link: 'https://zh-cn.namemc.com/',
      },
      {
        //icon: 'https://mcuuid.net/favicon.ico',
        icon: '/icons/nav/功能性网站/Minecraft UUID.ico',
        title: 'Minecraft UUID',
        desc: '查正版遊者UUID等資訊',
        link: 'https://mcuuid.net/',
      },
    ],
  },
  {
    title: '模組光影之加載器',
    items: [
      {
        //icon: 'https://forums.minecraftforge.net/favicon.ico',
        icon: '/icons/nav/模组和光影加载器/Forge.ico',
        title: 'Forge',
        desc: '模組加載器老鋪之官網',
        link: 'https://forums.minecraftforge.net/',
      },
      {
        //icon: 'https://neoforged.net/favicon.ico',
        icon: '/icons/nav/模组和光影加载器/NeoForge.ico',
        title: 'NeoForge',
        desc: 'Forge於高版之優良分支',
        link: 'https://neoforged.net/',
      },
      {
        //icon: 'https://fabricmc.net/assets/logo.png',
        icon: '/icons/nav/模组和光影加载器/Fabric.png',
        title: 'Fabric',
        desc: '新晉熱門之模組加載器',
        link: 'https://fabricmc.net/',
      },
      {
        //icon: 'https://quiltmc.org/favicon/favicon-32x32.png',
        icon: '/icons/nav/模组和光影加载器/Quilt.webp',
        title: 'Quilt',
        desc: 'Fabric之下游分支',
        link: 'https://quiltmc.org/en/',
      },
      {
        //icon: 'https://www.liteloader.com/favicon.ico',
        icon: '/icons/nav/模组和光影加载器/LiteLoader.ico',
        title: 'LiteLoader',
        desc: '輕量級模組加載器，久未新之',
        link: 'http://www.liteloader.com/',
      },
      {
        //icon: 'https://www.optifine.net/favicon.ico',
        icon: '/icons/nav/模组和光影加载器/Optifine.ico',
        title: 'Optifine',
        desc: '老牌渲染優化模組，亦可作光影加載器',
        link: 'https://www.optifine.net',
      },
      {
        //icon: 'https://cdn.modrinth.com/data/YL57xq9U/dc558eece920db435f9823ce86de0c4cde89800b.png',
        icon: '/icons/nav/模组和光影加载器/Iris Shaders.webp',
        title: 'Iris Shaders',
        desc: '以Fabric為引，Java高版之光影加載器，兼容於鈉',
        link: 'https://irisshaders.net/',
      },
    ],
  },
  {
    title: '啟動器與客戶端',
    items: [
      {
        //icon: 'https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/img/Launcher_Icon.png',
        icon: '/icons/nav/启动器和客户端/Minecraft 官方启动器.avif',
        title: 'Minecraft 官府啟動器',
        desc: 'MC官府啟動器',
        link: 'https://www.minecraft.net/zh-hans/download',
      },
      {
        //icon: 'https://hmcl.huangyuhui.net/favicon.ico',
        icon: '/icons/nav/启动器和客户端/HMCL.ico',
        title: 'HMCL',
        desc: '經典啟動器老鋪，跨平台',
        link: 'https://hmcl.huangyuhui.net/',
      },
      {
        //icon: '/icons/PCL2.png',
        icon: '/icons/nav/启动器和客户端/PCL2.png',
        title: 'PCL2',
        desc: '新晉啟動器，宜於新手',
        link: 'https://afdian.com/p/0164034c016c11ebafcb52540025c377',

      },
      {
        //icon: 'https://www.bakaxl.com/favicon.ico',
        icon: '/icons/nav/启动器和客户端/BakaXL.ico',
        title: 'BakaXL',
        desc: '國產二次元啟動器，界面甚美',
        link: 'https://www.bakaxl.com/',
      },
      {
        //icon: 'https://multimc.org/favicon.ico',
        icon: '/icons/nav/启动器和客户端/MultiMC.ico',
        title: 'MultiMC',
        desc: '海外啟動器老鋪，支持中文',
        link: 'https://multimc.org/',
      },
      {
        //icon: 'https://mc.163.com/favicon.ico',
        icon: '/icons/nav/启动器和客户端/中国版启动器.ico',
        title: '華夏版啟動器',
        desc: '華夏版官網',
        link: 'https://mc.163.com/',
      },
      {
        //icon: 'https://www.lunarclient.com/assets/img/favicon.ico',
        icon: '/icons/nav/启动器和客户端/Lunar Client.ico',
        title: 'Lunar Client',
        desc: '熱門PVP客戶端',
        link: 'https://www.lunarclient.com/',
      },
      {
        //icon: 'https://assets.badlion.net/site/favicon.webp',
        icon: '/icons/nav/启动器和客户端/Badlion Client.webp',
        title: 'Badlion Client',
        desc: '熱門PVP客戶端',
        link: 'https://client.badlion.net/zh-CN',
      },
      {
        //icon: 'https://labymod.net/page/tpl/assets/images/icons/favicon.ico',
        icon: '/icons/nav/启动器和客户端/Labymod.ico',
        title: 'Labymod',
        desc: '熱門PVP客戶端',
        link: 'https://labymod.net/zh_Hans',
      },
      {
        //icon: 'https://feathermc.com/favicon/apple-touch-icon.png',
        icon: '/icons/nav/启动器和客户端/FEATHER CLIENT.png',
        title: 'FEATHER CLIENT',
        desc: '熱門PVP客戶端',
        link: 'https://feathermc.com/',
      },
    ],
  },
  {
    title: '實用之器',
    items: [
      {
        icon: '/icons/nav/实用软件/EaglerCraft.webp',
        title: 'EaglerCraftX',
        desc: '網頁版MC，其本為JE1.8.8',
        link: 'https://eaglercraft.ru/',
      },
      {
        //icon: 'https://mccteam.github.io/icons/favicon-32x32.png',
        icon: '/icons/nav/实用软件/MCC.png',
        title: 'MCC',
        desc: 'MC命令行客戶端',
        link: 'https://mccteam.github.io/l10n/zh-Hans/',
      },
      {
        //icon: '/icons/MCA.png',
        icon: '/icons/nav/实用软件/MCA Selector.png',
        title: 'MCA Selector',
        desc: 'MC區塊選擇器，便於編輯區塊，支持中文',
        link: 'https://github.com/Querz/mcaselector',
      },
      {
        //icon: 'https://www.worldpainter.net/favicon.ico',
        icon: '/icons/nav/实用软件/WorldPainter.ico',
        title: 'WorldPainter',
        desc: 'MC地形製作之器',
        link: 'https://www.worldpainter.net/',
      },
      {
        //icon: 'https://www.radmin.com/favicon.svg',
        icon: '/icons/nav/实用软件/Radmin LAN.svg',
        title: 'Radmin LAN',
        desc: '虛擬局域網之器，可用於聯機',
        link: 'https://www.radmin.com/cn/',
      },
      {
        //icon: 'https://www.mineimator.com/images/logo.png',
        icon: '/icons/nav/实用软件/Mine-imator.png',
        title: 'Mine-imator',
        desc: 'MC動畫製作之器',
        link: 'https://www.mineimator.com/',
      },
      {
        //icon: 'https://mcreator.net/themes/mcreator/favicon.ico',
        icon: '/icons/nav/实用软件/MCreator.ico',
        title: 'MCreator',
        desc: '可視化MC模組製作之器',
        link: 'https://mcreator.net/',
      },
      {
        //icon: 'https://www.blockbench.net/favicon.svg',
        icon: '/icons/nav/实用软件/BlockBench.svg',
        title: 'BlockBench',
        desc: 'MC建模之器',
        link: 'https://www.blockbench.net/',
      },
      {
        //icon: 'https://serverpackcreator.de/icons/favicon-128x128.png',
        icon: '/icons/nav/实用软件/ServerPackCreator.png',
        title: 'ServerPackCreator',
        desc: '生成模組端伺服器核心',
        link: 'https://serverpackcreator.de/#/',
      },
    ],
  },
]
